### ISSUE TITLE
Python to Julia transpiler

### ISSUE THREAD

**Issue by kiwi0fruit** [JuliaLang/Juleps#55]
It would be nice to have Transpiler from subset of Python (and special ~pythonjulia module named like "Juthon") to complete Julia lang.

And a dream looks like it should both be:

1. A standalone transpiler so that the user can write "Juthon" package and contribute it to the Julia ecosystem by transpiling.
2. And runtime decorator style transpiler (with interface like Numba has) that calls Julia (or compiled python library in the future) from Python. So that a small piece of code can be added right in the Python app written in Python.

A good example of a transipiler from Python is [Transcrypt](https://github.com/QQuick/Transcrypt) that is a valid Python prior transpiling. But to achieve 1. this should be more like Julia in Python syntax (via IDE friendly mapping and juthon module with well-documented stubs) than attempt to implement Python's standard library.

The idea came from this discussion: [Why Julia? Will Python/Numba and Python/Cython lose to Julia?](https://github.com/numba/numba/issues/3814)

**Comment by kiwi0fruit** [comment]
@ViralBShah It was off topic there so I opened this issue.

**Comment by MikeInnes** [comment]
This is not really appropriate for a Julep, since it doesn't need to be in the core language; if you're interested in the idea you could do it as a package (see [LispSyntax.jl](https://github.com/swadey/LispSyntax.jl) for inspiration). If you want to discuss the idea you'd be welcome to do so on https://discourse.julialang.org.

**Comment by kiwi0fruit** [comment]
Thanks for the link to the discourse.

**Comment by StefanKarpinski** [comment]
Most of Julia's ability to resolve dynamism with performance comes from language design choices, not clever JIT technology. For example, Julia does not do tracing, it just analyzes code ahead of execution and generates good machine code from what you wrote. So transpiling Python to Julia would provide few performance benefits since you would still be stuck with all of the design choices in the Python language that make it so hard to execute efficiently. Don't take if from me, you can watch [this excellent talk](https://www.youtube.com/watch?v=qCGofLIzX6g) by Armin Ronacher on "How Python was Shaped by Leaky Internals" which does a much better job addressing the Python side of this issue than I ever could. For understanding the Julia side and how the language's design allows resolving performance with dynamism, there happens to be [a paper we wrote](http://janvitek.org/pubs/oopsla18b.pdf) on just that subject that you can check out.

**Comment by kiwi0fruit** [comment]
Sounds unreasonable if you you remember what a transpiler is. It's not an
interpreter. It's merely a mapping from one language to another. I bet
there is no Julia language construction (together with all optimization
flags) that cannot be written in valid Python (expect custom operators and
like) with decorators (or special transpiler directives like in Transcrypt).

>
Ideally transpiler maps some special Python dialect to Julia
near surjectively.

**Comment by kiwi0fruit** [comment]
UPD: Not simply Python dialect but dialect and subset of Python.

>

**Comment by KristofferC** [comment]
Again,

> If you want to discuss the idea you'd be welcome to do so on https://discourse.julialang.org.
